env = Environment(CPPXX='g++-4.7', CPPFLAGS='-std=c++11 -Wall -Wextra -pedantic -pedantic-errors -s -Ofast')
Default(env.Program('machine_translator',
    ['main.cpp',
     'decoder/decoder.cpp',
     'languagemodel/languagemodel.cpp',
     'converter/converter.cpp',
     'phrasetable/phrasetable.cpp',
	 'alignmentmodel/alignmentmodel.cpp']))
